import { prisma } from "../../lib/prisma";
import { PriceEditor } from "./PriceEditor";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  const [items, categoryCount, mediaCount, eurCount] = await Promise.all([
    prisma.product.findMany({ include: { translations: { where: { locale: "CS" } }, categories: { include: { category: { include: { translations: { where: { locale: "CS" } } } } } }, prices: { orderBy: { validFrom: "desc" } }, inventory: true }, orderBy: { createdAt: "asc" } }),
    prisma.category.count(), prisma.productMedia.count(), prisma.productPrice.count({ where: { currency: "EUR" } }),
  ]);
  return <main style={{ minHeight: "100vh", background: "#f4f0e9", color: "#173c3a", padding: "48px 6vw", fontFamily: "Arial, sans-serif" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: 24, marginBottom: 36 }}><div><small style={{ color: "#d9653b", letterSpacing: ".16em", fontWeight: 700 }}>ZEMBAG MALTA · ADMIN · POSTGRESQL</small><h1 style={{ fontSize: 48, letterSpacing: "-.05em", margin: "10px 0" }}>Catalog control center</h1><p style={{ color: "#68766f" }}>Live catalog from PostgreSQL. Source prices are reference data; Malta prices remain independently editable.</p></div><a href="/" style={{ color: "#173c3a", fontWeight: 700 }}>← storefront</a></header>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginBottom: 24 }}>{[["DATABASE PRODUCTS", items.length, "Imported catalog"], ["CATEGORIES", categoryCount, "PostgreSQL taxonomy"], ["LOCAL MEDIA", mediaCount, "Product media records"], ["MALTA EUR PRICES", eurCount || "Not set", "Requires approval"]].map(([label, value, note]) => <article key={String(label)} style={{ background: "#fffdf9", border: "1px solid #d9d4c9", borderRadius: 18, padding: 24 }}><small style={{ color: "#8b6a39", letterSpacing: ".12em", fontWeight: 700 }}>{label}</small><strong style={{ display: "block", fontSize: 32, margin: "12px 0 4px" }}>{value}</strong><span style={{ color: "#778179", fontSize: 13 }}>{note}</span></article>)}</section>
    <section style={{ background: "#fffdf9", border: "1px solid #d9d4c9", borderRadius: 18, padding: 24, overflow: "auto" }}><h2 style={{ marginTop: 0 }}>Database products</h2><table style={{ width: "100%", minWidth: 900, borderCollapse: "collapse", textAlign: "left" }}><thead><tr>{["Product", "SKU", "Category", "Source CZK", "Malta EUR", "Source stock", "Media"].map((x) => <th key={x} style={{ padding: 12, borderBottom: "1px solid #e8e2d8", fontSize: 11, color: "#7b827a" }}>{x}</th>)}</tr></thead><tbody>{items.map((item) => { const category = item.categories[0]?.category.translations[0]?.name ?? "—"; const price = item.prices.find((entry) => entry.currency === "CZK"); const euro = item.prices.find((entry) => entry.currency === "EUR"); return <tr key={item.id}><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8" }}><a href={`/product/p/${item.slug}`} style={{ color: "inherit" }}>{item.translations[0]?.name ?? item.slug}</a></td><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8" }}>{item.sku ?? "—"}</td><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8" }}>{category}</td><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8" }}>{price ? `${(price.amountMinor / 100).toFixed(2)} CZK` : "—"}</td><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8", color: "#a05b4d", fontWeight: 700 }}>{euro ? `${(euro.amountMinor / 100).toFixed(2)} EUR` : <PriceEditor productId={item.id} />}</td><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8" }}>{item.inventory?.source ?? "—"}</td><td style={{ padding: 12, borderBottom: "1px solid #e8e2d8" }}>local</td></tr> })}</tbody></table></section>
  </main>;
}
